/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainsRouteImport } from './routes/trains'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MyBookingsRouteImport } from './routes/my-bookings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HotelsRouteImport } from './routes/hotels'
import { Route as HolidaysRouteImport } from './routes/holidays'
import { Route as FlightsRouteImport } from './routes/flights'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CabsRouteImport } from './routes/cabs'
import { Route as BusesRouteImport } from './routes/buses'
import { Route as IndexRouteImport } from './routes/index'

const TrainsRoute = TrainsRouteImport.update({
  id: '/trains',
  path: '/trains',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBookingsRoute = MyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsRoute = HotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const HolidaysRoute = HolidaysRouteImport.update({
  id: '/holidays',
  path: '/holidays',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsRoute = FlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CabsRoute = CabsRouteImport.update({
  id: '/cabs',
  path: '/cabs',
  getParentRoute: () => rootRouteImport,
} as any)
const BusesRoute = BusesRouteImport.update({
  id: '/buses',
  path: '/buses',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buses': typeof BusesRoute
  '/cabs': typeof CabsRoute
  '/checkout': typeof CheckoutRoute
  '/flights': typeof FlightsRoute
  '/holidays': typeof HolidaysRoute
  '/hotels': typeof HotelsRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/trains': typeof TrainsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buses': typeof BusesRoute
  '/cabs': typeof CabsRoute
  '/checkout': typeof CheckoutRoute
  '/flights': typeof FlightsRoute
  '/holidays': typeof HolidaysRoute
  '/hotels': typeof HotelsRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/trains': typeof TrainsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buses': typeof BusesRoute
  '/cabs': typeof CabsRoute
  '/checkout': typeof CheckoutRoute
  '/flights': typeof FlightsRoute
  '/holidays': typeof HolidaysRoute
  '/hotels': typeof HotelsRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/trains': typeof TrainsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buses'
    | '/cabs'
    | '/checkout'
    | '/flights'
    | '/holidays'
    | '/hotels'
    | '/login'
    | '/my-bookings'
    | '/profile'
    | '/register'
    | '/trains'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buses'
    | '/cabs'
    | '/checkout'
    | '/flights'
    | '/holidays'
    | '/hotels'
    | '/login'
    | '/my-bookings'
    | '/profile'
    | '/register'
    | '/trains'
  id:
    | '__root__'
    | '/'
    | '/buses'
    | '/cabs'
    | '/checkout'
    | '/flights'
    | '/holidays'
    | '/hotels'
    | '/login'
    | '/my-bookings'
    | '/profile'
    | '/register'
    | '/trains'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusesRoute: typeof BusesRoute
  CabsRoute: typeof CabsRoute
  CheckoutRoute: typeof CheckoutRoute
  FlightsRoute: typeof FlightsRoute
  HolidaysRoute: typeof HolidaysRoute
  HotelsRoute: typeof HotelsRoute
  LoginRoute: typeof LoginRoute
  MyBookingsRoute: typeof MyBookingsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  TrainsRoute: typeof TrainsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trains': {
      id: '/trains'
      path: '/trains'
      fullPath: '/trains'
      preLoaderRoute: typeof TrainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bookings': {
      id: '/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof MyBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels': {
      id: '/hotels'
      path: '/hotels'
      fullPath: '/hotels'
      preLoaderRoute: typeof HotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holidays': {
      id: '/holidays'
      path: '/holidays'
      fullPath: '/holidays'
      preLoaderRoute: typeof HolidaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights': {
      id: '/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof FlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabs': {
      id: '/cabs'
      path: '/cabs'
      fullPath: '/cabs'
      preLoaderRoute: typeof CabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buses': {
      id: '/buses'
      path: '/buses'
      fullPath: '/buses'
      preLoaderRoute: typeof BusesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusesRoute: BusesRoute,
  CabsRoute: CabsRoute,
  CheckoutRoute: CheckoutRoute,
  FlightsRoute: FlightsRoute,
  HolidaysRoute: HolidaysRoute,
  HotelsRoute: HotelsRoute,
  LoginRoute: LoginRoute,
  MyBookingsRoute: MyBookingsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  TrainsRoute: TrainsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
